-- =====================================================================
-- RiveraQuest Safaris - Step 5: import the sample data of Assignment 01 Part 02 (Part C)
-- into the live BoatSafariDB, mapped to the table and column names the application uses.
--
-- BEFORE YOU RUN
--   1. Take a backup (SSMS: right-click BoatSafariDB > Tasks > Back Up).
--   2. Restart the application once so the new maintenance_logs columns exist
--      (end_date, maintenance_type).
-- WHAT IT DOES
--   * Adds the PDF rows ON TOP of your existing rows; nothing existing is changed or deleted.
--   * New ids are generated by the database; every link between rows is re-mapped
--     (PDF customer 3 may become customer 7 here, and its bookings follow it).
--   * Everything runs in ONE transaction: if anything fails, nothing is saved.
--   * It refuses to run twice (it stops if the PDF customer amal.perera@gmail.com exists).
--   * All imported customers and staff get the demo password  Demo@1234  (stored as a bcrypt hash).
--   * Trips of status Scheduled are shifted forward so the earliest one is 3 days from today
--     (so they can be booked); Completed and Cancelled trips keep their original dates.
-- The result sets at the end show the rows added per table next to the PDF counts.
-- =====================================================================
USE BoatSafariDB;
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF EXISTS (SELECT 1 FROM customers WHERE email = 'amal.perera@gmail.com')
    THROW 50010, 'The PDF data is already imported (customer amal.perera@gmail.com exists). Nothing was changed.', 1;
IF COL_LENGTH('maintenance_logs', 'end_date') IS NULL OR COL_LENGTH('maintenance_logs', 'maintenance_type') IS NULL
    THROW 50011, 'Restart the application first so maintenance_logs gets the end_date and maintenance_type columns.', 1;

DECLARE @shift INT = DATEDIFF(DAY, '2026-09-22', CAST(GETDATE() AS DATE)) + 3;
DECLARE @pwd VARCHAR(255) = '$2a$10$bY.azeYwcUtIwgAGqpwJAuPHvXD4oIgM0nrdwx8.7/rJN8kbx61nm';
DECLARE @triggerWasOn BIT = CASE WHEN EXISTS (SELECT 1 FROM sys.triggers WHERE name = 'trg_bookings_audit' AND is_disabled = 0) THEN 1 ELSE 0 END;

CREATE TABLE #log (step NVARCHAR(60), pdfRows INT, addedRows INT);
CREATE TABLE #m_customer (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_staff    (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_route    (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_guide    (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_crew     (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_boat     (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_trip     (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_promo    (pdf INT PRIMARY KEY, id BIGINT);
CREATE TABLE #m_booking  (pdf INT PRIMARY KEY, id BIGINT);

BEGIN TRY
BEGIN TRANSACTION;
IF @triggerWasOn = 1 DISABLE TRIGGER dbo.trg_bookings_audit ON dbo.bookings;

MERGE customers AS t
USING (VALUES
    (1, N'Amal', N'Perera', 'amal.perera@gmail.com', @pwd, N'45 Galle Road', N'Colombo', N'Sri Lanka', '2026-01-12', 'Active', '0771000001'),
    (2, N'Kavya', N'Nanayakkara', 'kavya.n@gmail.com', @pwd, N'12 Temple Road', N'Kandy', N'Sri Lanka', '2026-02-03', 'Active', '0771000002'),
    (3, N'Sithum', N'Rajapaksha', 'sithum.raja@yahoo.com', @pwd, N'78 Beach Road', N'Galle', N'Sri Lanka', '2026-02-20', 'Active', '0771000003'),
    (4, N'Nimali', N'Fernando', 'nimali.fernando@gmail.com', @pwd, N'5 Lake Drive', N'Negombo', N'Sri Lanka', '2026-03-08', 'Active', '0771000004'),
    (5, N'John', N'Smith', 'john.smith@outlook.com', @pwd, N'221 Baker Street', N'London', N'United Kingdom', '2026-04-15', 'Active', '+447700900101'),
    (6, N'Emily', N'Clarke', 'emily.clarke@gmail.com', @pwd, NULL, N'Sydney', N'Australia', '2026-05-22', 'Active', '+61400000106'),
    (7, N'Ravindu', N'Senaratne', 'ravindu.s@gmail.com', @pwd, N'33 Main Street', N'Matara', N'Sri Lanka', '2026-07-01', 'Active', '0771000007'),
    (8, N'Hansika', N'Ekanayake', 'hansika.e@gmail.com', @pwd, NULL, NULL, NULL, '2026-08-10', 'Inactive', '0771000008')
) AS s(pdf, first_name, last_name, email, pwd, street, city, country, registration_date, account_status, phone_number)
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT (first_name, last_name, email, password_hash, street, city, country, registration_date, account_status, phone_number)
    VALUES (s.first_name, s.last_name, s.email, s.pwd, s.street, s.city, s.country, s.registration_date, s.account_status, s.phone_number)
OUTPUT s.pdf, inserted.id INTO #m_customer(pdf, id);
INSERT INTO #log VALUES (N'customers', 8, @@ROWCOUNT);

MERGE staff AS t
USING (VALUES
    (1, N'Nuwan Perera', 'nuwan.perera@boatsafari.lk', @pwd, '2021-01-15', 'Administrator'),
    (2, N'Tharushi Senanayake', 'tharushi.senanayake@boatsafari.lk', @pwd, '2021-03-01', 'Administrator'),
    (3, N'Kasun Wickramasinghe', 'kasun.wickramasinghe@boatsafari.lk', @pwd, '2021-02-10', 'Administrator'),
    (4, N'Dilani Jayawardena', 'dilani.jayawardena@boatsafari.lk', @pwd, '2021-04-20', 'Administrator'),
    (5, N'Ruwan Fernando', 'ruwan.fernando@boatsafari.lk', @pwd, '2023-01-09', 'Administrator'),
    (6, N'Chamara Silva', 'chamara.silva@boatsafari.lk', @pwd, '2021-05-12', 'FleetManager'),
    (7, N'Anjali Rathnayake', 'anjali.rathnayake@boatsafari.lk', @pwd, '2022-04-04', 'FleetManager'),
    (8, N'Sampath Kumara', 'sampath.kumara@boatsafari.lk', @pwd, '2022-09-19', 'FleetManager'),
    (9, N'Malsha Gunasekara', 'malsha.gunasekara@boatsafari.lk', @pwd, '2023-03-27', 'FleetManager'),
    (10, N'Prasad Herath', 'prasad.herath@boatsafari.lk', @pwd, '2024-01-15', 'FleetManager'),
    (11, N'Isuru Bandara', 'isuru.bandara@boatsafari.lk', @pwd, '2021-07-05', 'SafetyOfficer'),
    (12, N'Nadeesha Weerasinghe', 'nadeesha.weerasinghe@boatsafari.lk', @pwd, '2022-01-24', 'SafetyOfficer'),
    (13, N'Lahiru Dissanayake', 'lahiru.dissanayake@boatsafari.lk', @pwd, '2022-11-14', 'SafetyOfficer'),
    (14, N'Sewwandi Amarasinghe', 'sewwandi.amarasinghe@boatsafari.lk', @pwd, '2023-05-22', 'SafetyOfficer'),
    (15, N'Thilina Karunaratne', 'thilina.karunaratne@boatsafari.lk', @pwd, '2024-03-11', 'SafetyOfficer'),
    (16, N'Hiruni De Silva', 'hiruni.desilva@boatsafari.lk', @pwd, '2021-09-13', 'MarketingOfficer'),
    (17, N'Yasas Liyanage', 'yasas.liyanage@boatsafari.lk', @pwd, '2022-08-01', 'MarketingOfficer'),
    (18, N'Ishara Madushani', 'ishara.madushani@boatsafari.lk', @pwd, '2023-02-06', 'MarketingOfficer'),
    (19, N'Buddhika Ranasinghe', 'buddhika.ranasinghe@boatsafari.lk', @pwd, '2023-10-30', 'MarketingOfficer'),
    (20, N'Oshadi Kulathunga', 'oshadi.kulathunga@boatsafari.lk', @pwd, '2024-06-03', 'MarketingOfficer'),
    (21, N'Kavindu Jayasinghe', 'kavindu.jayasinghe@boatsafari.lk', @pwd, '2021-11-08', 'BookingOfficer'),
    (22, N'Sanduni Peiris', 'sanduni.peiris@boatsafari.lk', @pwd, '2022-05-16', 'BookingOfficer'),
    (23, N'Dinuka Abeysekara', 'dinuka.abeysekara@boatsafari.lk', @pwd, '2023-04-17', 'BookingOfficer'),
    (24, N'Menaka Wijesinghe', 'menaka.wijesinghe@boatsafari.lk', @pwd, '2024-02-19', 'BookingOfficer'),
    (25, N'Tharindu Gamage', 'tharindu.gamage@boatsafari.lk', @pwd, '2025-01-13', 'BookingOfficer')
) AS s(pdf, name, email, pwd, hire_date, staff_type)
ON 1 = 0
WHEN NOT MATCHED THEN
    INSERT (name, email, password_hash, hire_date, staff_type)
    VALUES (s.name, s.email, s.pwd, s.hire_date, s.staff_type)
OUTPUT s.pdf, inserted.id INTO #m_staff(pdf, id);
INSERT INTO #log VALUES (N'staff', 25, @@ROWCOUNT);

UPDATE st SET supervisor_id = ms.id
FROM staff st
JOIN #m_staff me ON me.id = st.id
JOIN (VALUES (2,1), (3,1), (4,1), (5,1), (6,1), (7,6), (8,6), (9,6), (10,6), (11,2), (12,11), (13,11), (14,11), (15,11), (16,3), (17,16), (18,16), (19,16), (20,16), (21,4), (22,21), (23,21), (24,21), (25,21)) AS v(pdf, sup) ON v.pdf = me.pdf
JOIN #m_staff ms ON ms.pdf = v.sup;

INSERT INTO booking_officers (id, desk_number)
SELECT m.id, v.val FROM (VALUES (21, 'D-01'), (22, 'D-02'), (23, 'D-03'), (24, 'D-04'), (25, 'D-05')) AS v(pdf, val)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'booking_officers', 5, @@ROWCOUNT);

INSERT INTO fleet_managers (id, certification_number)
SELECT m.id, v.val FROM (VALUES (6, 'FM-2021-001'), (7, 'FM-2021-002'), (8, 'FM-2022-003'), (9, 'FM-2022-004'), (10, 'FM-2023-005')) AS v(pdf, val)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'fleet_managers', 5, @@ROWCOUNT);

INSERT INTO safety_officers (id, safety_license_no)
SELECT m.id, v.val FROM (VALUES (11, 'SO-LIC-1101'), (12, 'SO-LIC-1102'), (13, 'SO-LIC-1103'), (14, 'SO-LIC-1104'), (15, 'SO-LIC-1105')) AS v(pdf, val)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'safety_officers', 5, @@ROWCOUNT);

INSERT INTO marketing_officers (id, department)
SELECT m.id, v.val FROM (VALUES (16, N'Digital Marketing'), (17, N'Promotions'), (18, N'Customer Relations'), (19, N'Partnerships'), (20, N'Brand and Events')) AS v(pdf, val)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'marketing_officers', 5, @@ROWCOUNT);

INSERT INTO administrators (id, access_level)
SELECT m.id, v.val FROM (VALUES (1, 'Full'), (2, 'Full'), (3, 'Limited'), (4, 'Limited'), (5, 'Limited')) AS v(pdf, val)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'administrators', 5, @@ROWCOUNT);

INSERT INTO staff_contact_numbers (staff_id, contact_number)
SELECT m.id, v.num FROM (VALUES (1,'0771234501'), (1,'0112345601'), (2,'0771234502'), (6,'0771234506'), (7,'0771234507'), (11,'0771234511'), (16,'0771234516'), (21,'0771234521'), (21,'0112345621')) AS v(pdf, num)
JOIN #m_staff m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'staff_contact_numbers', 9, @@ROWCOUNT);

INSERT INTO customer_phones (customer_id, phone_number)
SELECT m.id, v.num FROM (VALUES (1,'0771000001'), (1,'0112000001'), (2,'0771000002'), (3,'0771000003'), (4,'0771000004'), (5,'+447700900101'), (6,'+61400000106'), (7,'0771000007'), (8,'0771000008')) AS v(pdf, num)
JOIN #m_customer m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'customer_phones', 9, @@ROWCOUNT);

INSERT INTO emergency_contacts (customer_id, contact_id, contact_name, relationship)
SELECT m.id, v.cid, v.nm, v.rel FROM (VALUES (1,1,N'Kamal Perera',N'Father'), (2,1,N'Sunil Nanayakkara',N'Husband'), (3,1,N'Rasika Rajapaksha',N'Mother'), (4,1,N'Ajith Fernando',N'Brother'), (5,1,N'Mary Smith',N'Wife'), (5,2,N'Peter Smith',NULL)) AS v(pdf, cid, nm, rel)
JOIN #m_customer m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'emergency_contacts', 6, @@ROWCOUNT);

INSERT INTO emergency_contact_phones (customer_id, contact_id, phone_number)
SELECT m.id, v.cid, v.num FROM (VALUES (1,1,'0772000001'), (1,1,'0112000101'), (2,1,'0772000002'), (3,1,'0772000003'), (4,1,'0772000004'), (5,1,'+447700900201'), (5,2,'+447700900202')) AS v(pdf, cid, num)
JOIN #m_customer m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'emergency_contact_phones', 7, @@ROWCOUNT);

MERGE routes AS t USING (VALUES
    (1,N'Bentota Jetty',N'Bentota Ganga Estuary',8.5),
    (2,N'Madu Ganga Jetty, Balapitiya',N'Madu Ganga Islands',12.0),
    (3,N'Mirissa Harbour',N'Whale Watching Area',22.0),
    (4,N'Kalpitiya Jetty',N'Bar Reef Dolphin Area',15.5),
    (5,N'Negombo Lagoon Jetty',N'Muthurajawela Wetland',10.0),
    (6,N'Koggala Lake Jetty',N'Koggala Lake Islands',6.5)
) AS s(pdf, origin, destination, km) ON 1 = 0
WHEN NOT MATCHED THEN INSERT (origin, destination, distance_km) VALUES (s.origin, s.destination, s.km)
OUTPUT s.pdf, inserted.id INTO #m_route(pdf, id);
INSERT INTO #log VALUES (N'routes', 6, @@ROWCOUNT);

MERGE guides AS t USING (VALUES
    (1,N'Saman Kumara','2019-03-10'),
    (2,N'Nirosha Perera','2020-06-01'),
    (3,N'Rohan Fernando','2021-09-15'),
    (4,N'Chathurika Silva','2022-11-20'),
    (5,N'Tharaka Bandara','2024-02-05')
) AS s(pdf, name, join_date) ON 1 = 0
WHEN NOT MATCHED THEN INSERT (name, join_date) VALUES (s.name, s.join_date)
OUTPUT s.pdf, inserted.id INTO #m_guide(pdf, id);
INSERT INTO #log VALUES (N'guides', 5, @@ROWCOUNT);

MERGE crews AS t USING (VALUES
    (1,N'Wasantha Kumara','Captain','CAP-2018-101'),
    (2,N'Lalith Perera','Deckhand','DEK-2020-102'),
    (3,N'Ajith Rajapaksha','Captain','CAP-2017-103'),
    (4,N'Ruwan Silva','Deckhand','DEK-2021-104'),
    (5,N'Nishantha Fernando','Captain','CAP-2015-105'),
    (6,N'Gayan Madushanka','Engineer','ENG-2019-106'),
    (7,N'Sisira Jayalath','Captain','CAP-2019-107'),
    (8,N'Dilhara Weerakoon','Lifeguard','LIF-2022-108')
) AS s(pdf, name, role, license) ON 1 = 0
WHEN NOT MATCHED THEN INSERT (name, role, license_number) VALUES (s.name, s.role, s.license)
OUTPUT s.pdf, inserted.id INTO #m_crew(pdf, id);
INSERT INTO #log VALUES (N'crews', 8, @@ROWCOUNT);

INSERT INTO guide_languages (guide_id, language)
SELECT m.id, v.lang FROM (VALUES (1,N'Sinhala'), (1,N'English'), (2,N'Sinhala'), (2,N'English'), (2,N'German'), (3,N'Tamil'), (3,N'English'), (4,N'Sinhala'), (4,N'French'), (5,N'English'), (5,N'Japanese')) AS v(pdf, lang)
JOIN #m_guide m ON m.pdf = v.pdf;
INSERT INTO #log VALUES (N'guide_languages', 11, @@ROWCOUNT);

MERGE boats AS t
USING (SELECT s0.*, mf.id AS fm_id
  FROM (VALUES
    (1,N'Ganga Queen','BS-1001-WP',20,'AVAILABLE','GOOD','Yamaha 200HP Outboard','Cleared',N'Wasantha Kumara',2,'2026-08-12',6),
    (2,N'Madu Explorer','BS-1002-SP',12,'AVAILABLE','GOOD','Suzuki 115HP Outboard','Cleared',N'Ajith Rajapaksha',2,'2026-06-16',7),
    (3,N'Blue Whale','BS-1003-SP',30,'MAINTENANCE','NEEDS_SERVICE','Cummins Inboard Diesel','Cleared',N'Nishantha Fernando',2,NULL,8),
    (4,N'Lagoon Runner','BS-1004-WP',10,'AVAILABLE','GOOD','Honda 90HP Outboard','Not Cleared',N'Not assigned',1,'2026-07-22',9),
    (5,N'Dolphin Star','BS-1005-NW',25,'AVAILABLE','GOOD','Yamaha 250HP Outboard','Cleared',N'Sisira Jayalath',2,'2026-05-06',10),
    (6,N'Old Mariner','BS-1006-SP',8,'DECOMMISSIONED','GOOD','Mercury 60HP Outboard','Cleared',N'Not assigned',0,'2026-01-25',6)
  ) AS s0(pdf, name, reg, cap, status, engine_status, engine_type, safety_status, captain, crew_count, last_maint, fm)
  LEFT JOIN #m_staff mf ON mf.pdf = s0.fm
) AS s
ON 1 = 0
WHEN NOT MATCHED THEN INSERT (name, registration_number, capacity, status, engine_status, fuel_level_percentage, captain_name, crew_count, last_maintenance_date, engine_type, safety_status, fleet_manager_id)
VALUES (s.name, s.reg, s.cap, s.status, s.engine_status, 100.0, s.captain, s.crew_count, s.last_maint, s.engine_type, s.safety_status, s.fm_id)
OUTPUT s.pdf, inserted.id INTO #m_boat(pdf, id);
INSERT INTO #log VALUES (N'boats', 6, @@ROWCOUNT);

INSERT INTO crew_assignments (crew_id, boat_id, assignment_date)
SELECT mc.id, mb.id, v.dt FROM (VALUES (1,1,'2025-01-10'), (2,1,'2025-01-10'), (3,2,'2025-03-15'), (4,2,'2025-03-15'), (5,3,'2024-11-01'), (6,3,'2024-11-01'), (7,5,'2025-06-20'), (8,5,'2025-06-20'), (4,4,'2026-07-25')) AS v(crew, boat, dt)
JOIN #m_crew mc ON mc.pdf = v.crew JOIN #m_boat mb ON mb.pdf = v.boat;
INSERT INTO #log VALUES (N'crew_assignments', 9, @@ROWCOUNT);

INSERT INTO maintenance_logs (boat_id, maintenance_date, end_date, maintenance_type, description, cost, performed_by, status)
SELECT mb.id, v.d1, v.d2, v.typ, v.descr, v.cost, N'Fleet workshop', v.st FROM (VALUES
    (1,'2026-03-01','2026-03-03',N'Engine Service',N'Routine 200-hour engine service',45000.0,'COMPLETED'),
    (1,'2026-08-10','2026-08-12',N'Hull Inspection',N'Hull cleaning and inspection',30000.0,'COMPLETED'),
    (2,'2026-06-15','2026-06-16',N'Engine Service',N'Oil and filter change',18000.0,'COMPLETED'),
    (3,'2026-09-21','2026-10-05',N'Major Overhaul',N'Inboard engine overhaul',350000.0,'SCHEDULED'),
    (4,'2026-07-20','2026-07-22',N'Propeller Repair',N'Propeller Repair',22000.0,'COMPLETED'),
    (5,'2026-05-05','2026-05-06',N'Safety Equipment Check',N'Annual safety equipment check',12000.0,'COMPLETED'),
    (5,'2026-10-12','2026-10-13',N'Engine Service',N'Routine service',40000.0,'SCHEDULED'),
    (6,'2026-01-10','2026-01-25',N'Major Overhaul',N'Boat retired after overhaul',210000.0,'COMPLETED')
) AS v(boat, d1, d2, typ, descr, cost, st)
JOIN #m_boat mb ON mb.pdf = v.boat;
INSERT INTO #log VALUES (N'maintenance_logs', 8, @@ROWCOUNT);

MERGE trips AS t
USING (SELECT s0.*, mb.id AS boat_id, mr.id AS route_id, mg.id AS guide_id
  FROM (VALUES
    (1,CAST('2026-09-05' AS DATE),'08:00:00','10:00:00',5500.0,18,'Completed',1,1,1,6),
    (2,CAST('2026-09-08' AS DATE),'15:30:00','17:30:00',6000.0,10,'Completed',2,2,2,5),
    (3,CAST('2026-09-12' AS DATE),'06:00:00','10:00:00',12500.0,28,'Completed',3,3,3,7),
    (4,CAST('2026-09-16' AS DATE),'09:00:00','11:00:00',5000.0,8,'Cancelled',4,5,4,0),
    (5,CAST(DATEADD(DAY, @shift, '2026-09-22') AS DATE),'08:30:00','10:30:00',5500.0,18,'Scheduled',1,1,1,6),
    (6,CAST(DATEADD(DAY, @shift, '2026-09-26') AS DATE),'07:00:00','10:30:00',9500.0,22,'Scheduled',5,4,5,6),
    (7,CAST(DATEADD(DAY, @shift, '2026-09-28') AS DATE),'16:00:00','18:00:00',6000.0,10,'Scheduled',2,2,NULL,2),
    (8,CAST(DATEADD(DAY, @shift, '2026-10-03') AS DATE),'08:00:00','09:30:00',4500.0,15,'Scheduled',1,6,2,3)
  ) AS s0(pdf, trip_date, dep, arr, price, cap, status, boat, route, guide, booked)
  LEFT JOIN #m_boat mb ON mb.pdf = s0.boat
LEFT JOIN #m_route mr ON mr.pdf = s0.route
LEFT JOIN #m_guide mg ON mg.pdf = s0.guide
) AS s
ON 1 = 0
WHEN NOT MATCHED THEN INSERT (trip_date, departure_time, arrival_time, price, passenger_capacity, status, boat_id, route_id, guide_id, booked_seats)
VALUES (s.trip_date, s.dep, s.arr, s.price, s.cap, s.status, s.boat_id, s.route_id, s.guide_id, s.booked)
OUTPUT s.pdf, inserted.id INTO #m_trip(pdf, id);
INSERT INTO #log VALUES (N'trips', 8, @@ROWCOUNT);

MERGE promotions AS t
USING (SELECT s0.*, ms.id AS created_id
  FROM (VALUES
    (1,'EARLYBIRD20',N'Early Bird Discount',N'Early bird offer: 20% off selected trips','PERCENTAGE',20.0,NULL,'2026-08-01','2026-10-31',1,2,'ACTIVE','Published',16),
    (2,'MONSOON500',N'Monsoon Special',N'LKR 500 off any river safari','FIXED_AMOUNT',NULL,500.0,'2026-09-01','2026-10-15',1,2,'ACTIVE','Published',17),
    (3,'FAMILY15',N'Family Fun Offer',N'15% off for bookings of 4 or more seats','PERCENTAGE',15.0,NULL,'2026-07-01','2026-12-31',1,2,'ACTIVE','Published',18),
    (4,'SUMMER25',N'Summer Splash',N'25% summer offer','PERCENTAGE',25.0,NULL,'2026-04-01','2026-06-30',0,0,'EXPIRED','Archived',19),
    (5,'NEWYEAR30',N'New Year Festival',NULL,'PERCENTAGE',30.0,NULL,'2026-12-15','2027-01-15',0,0,'INACTIVE','Draft',20),
    (6,'LOYAL1000',N'Loyalty Reward',N'LKR 1000 off for returning customers','FIXED_AMOUNT',NULL,1000.0,'2026-09-01','2026-11-30',1,1,'ACTIVE','Published',16)
  ) AS s0(pdf, code, title, descr, dtype, pct, amt, vf, vt, active, used, status, report_status, createdby)
  LEFT JOIN #m_staff ms ON ms.pdf = s0.createdby
) AS s
ON 1 = 0
WHEN NOT MATCHED THEN INSERT (code, title, description, discount_type, discount_percentage, fixed_amount, valid_from, valid_until, active, usage_count, status, report_status, created_by)
VALUES (s.code, s.title, s.descr, s.dtype, s.pct, s.amt, s.vf, s.vt, s.active, s.used, s.status, s.report_status, s.created_id)
OUTPUT s.pdf, inserted.id INTO #m_promo(pdf, id);
INSERT INTO #log VALUES (N'promotions', 6, @@ROWCOUNT);

INSERT INTO promotion_trips (promotion_id, trip_id)
SELECT mp.id, mt.id FROM (VALUES (1,3), (1,5), (1,6), (1,8), (2,2), (2,5), (2,7), (3,1), (3,5), (3,6), (6,8)) AS v(promo, trip)
JOIN #m_promo mp ON mp.pdf = v.promo JOIN #m_trip mt ON mt.pdf = v.trip;
INSERT INTO #log VALUES (N'promotion_trips', 11, @@ROWCOUNT);

MERGE bookings AS t
USING (SELECT s0.*, mc.id AS cust_id, mt.id AS trip_id, mp.id AS promo_id, mo.id AS officer_id
  FROM (VALUES
    (1,'BK-2026-9001',1,1,2,'S-01, S-02',11000.0,0.0,11000.0,'2026-08-20T10:00:00','COMPLETED','VALIDATED',NULL,'ONLINE_CARD',NULL,NULL,NULL),
    (2,'BK-2026-9002',2,1,4,'S-03, S-04, S-05, S-06',22000.0,3300.0,18700.0,'2026-08-25T10:00:00','COMPLETED','VALIDATED',NULL,'ONLINE_CARD',NULL,3,NULL),
    (3,'BK-2026-9003',3,2,3,'S-01, S-02, S-03',18000.0,500.0,17500.0,'2026-09-01T10:00:00','COMPLETED','VALIDATED',NULL,'CASH_COUNTER',N'Walk-in booking processed by Kavindu Jayasinghe',2,21),
    (4,'BK-2026-9004',5,3,2,'S-01, S-02',25000.0,5000.0,20000.0,'2026-08-30T10:00:00','COMPLETED','VALIDATED',NULL,'ONLINE_CARD',NULL,1,NULL),
    (5,'BK-2026-9005',6,3,5,'S-03, S-04, S-05, S-06, S-07',62500.0,0.0,62500.0,'2026-09-02T10:00:00','COMPLETED','VALIDATED',NULL,'ONLINE_CARD',NULL,NULL,NULL),
    (6,'BK-2026-9006',4,4,3,NULL,15000.0,0.0,15000.0,'2026-09-10T10:00:00','CANCELLED','VALIDATED','Trip cancelled by the operator','ONLINE_CARD',NULL,NULL,NULL),
    (7,'BK-2026-9007',1,5,4,'S-01, S-02, S-03, S-04',22000.0,3300.0,18700.0,'2026-09-10T10:00:00','CONFIRMED','VALIDATED',NULL,'ONLINE_CARD',NULL,3,NULL),
    (8,'BK-2026-9008',7,5,2,'S-05, S-06',11000.0,0.0,11000.0,'2026-09-15T10:00:00','PENDING','PENDING_VALIDATION',NULL,'CASH_COUNTER',N'Walk-in booking processed by Sanduni Peiris',NULL,22),
    (9,'BK-2026-9009',3,6,6,'S-01, S-02, S-03, S-04, S-05, S-06',57000.0,11400.0,45600.0,'2026-09-17T10:00:00','CONFIRMED','VALIDATED',NULL,'ONLINE_CARD',NULL,1,NULL),
    (10,'BK-2026-9010',5,7,2,'S-01, S-02',12000.0,500.0,11500.0,'2026-09-18T10:00:00','PENDING','PENDING_VALIDATION',NULL,'ONLINE_CARD',NULL,2,NULL),
    (11,'BK-2026-9011',2,8,3,'S-01, S-02, S-03',13500.0,1000.0,12500.0,'2026-09-18T10:00:00','PENDING','PENDING_VALIDATION',NULL,'CASH_COUNTER',N'Walk-in booking processed by Dinuka Abeysekara',6,23),
    (12,'BK-2026-9012',7,2,2,'S-04, S-05',12000.0,0.0,12000.0,'2026-09-03T10:00:00','COMPLETED','VALIDATED',NULL,'CASH_COUNTER',N'Walk-in booking processed by Menaka Wijesinghe',NULL,24)
  ) AS s0(pdf, ref, cust, trip, seats_n, seat_labels, gross, disc, final, bdate, status, vstatus, creason, pay, notes, promo, officer)
  LEFT JOIN #m_customer mc ON mc.pdf = s0.cust
LEFT JOIN #m_trip mt ON mt.pdf = s0.trip
LEFT JOIN #m_promo mp ON mp.pdf = s0.promo
LEFT JOIN #m_staff mo ON mo.pdf = s0.officer
) AS s
ON 1 = 0
WHEN NOT MATCHED THEN INSERT (booking_reference, customer_id, trip_id, seat_count, seat_numbers, total_price, discount_amount, final_price, booking_date, status, validation_status, cancellation_reason, payment_method, notes, promotion_id, booking_officer_id)
VALUES (s.ref, s.cust_id, s.trip_id, s.seats_n, s.seat_labels, s.gross, s.disc, s.final, s.bdate, s.status, s.vstatus, s.creason, s.pay, s.notes, s.promo_id, s.officer_id)
OUTPUT s.pdf, inserted.id INTO #m_booking(pdf, id);
INSERT INTO #log VALUES (N'bookings', 12, @@ROWCOUNT);

INSERT INTO reviews (customer_id, trip_id, rating, comment, review_date, approved, status)
SELECT mc.id, mt.id, v.rating, v.cmt, v.rdate, 1, 'NEW' FROM (VALUES
    (1,1,5,N'Amazing estuary trip! We saw many birds.','2026-09-06T09:00:00'),
    (2,1,4,N'Great guide, but the boat was a little crowded.','2026-09-06T09:00:00'),
    (3,2,5,N'Perfect trip for the whole family.','2026-09-09T09:00:00'),
    (5,3,5,N'We saw blue whales. Unforgettable!','2026-09-13T09:00:00'),
    (6,3,4,NULL,'2026-09-14T09:00:00'),
    (7,2,3,N'The boat left 15 minutes late.','2026-09-09T09:00:00')
) AS v(cust, trip, rating, cmt, rdate)
JOIN #m_customer mc ON mc.pdf = v.cust JOIN #m_trip mt ON mt.pdf = v.trip;
INSERT INTO #log VALUES (N'reviews', 6, @@ROWCOUNT);

INSERT INTO reports (report_type, generated_date, summary_data, compiled_by)
SELECT v.typ, v.gdate, v.summ, ms.id FROM (VALUES
    ('Booking Summary','2026-09-19',N'Bookings: 12. Completed 6, Confirmed 2, Pending 3, Cancelled 1.',1),
    ('Revenue Report','2026-09-19',N'Revenue from 6 completed bookings: LKR 141,700.00.',2),
    ('Fleet Utilisation','2026-09-19',N'Trips: 3 completed, 1 cancelled, 4 scheduled. Most used boat: Ganga Queen (3 trips).',3),
    ('Safety Compliance','2026-09-19',N'Checklists recorded: 6. Cleared 3, Not Cleared 1, Pending 2.',4),
    ('Promotion Performance','2026-09-19',N'Promotions: 6 (Published 4, Archived 1, Draft 1). Bookings that used a promotion: 7.',5)
) AS v(typ, gdate, summ, adm)
JOIN #m_staff ms ON ms.pdf = v.adm;
INSERT INTO #log VALUES (N'reports', 5, @@ROWCOUNT);

INSERT INTO trip_safety_contacts (trip_id, contact_id, contact_name, contact_type)
SELECT mt.id, v.cid, v.nm, v.typ FROM (VALUES (1,1,N'Bentota Coast Guard Post',N'Coast Guard'), (2,1,N'Balapitiya Police Station',N'Police'), (3,1,N'Mirissa Harbour Office',N'Harbour Authority'), (3,2,N'Matara General Hospital',N'Hospital'), (4,1,N'Negombo Police Station',N'Police'), (5,1,N'Bentota Coast Guard Post',N'Coast Guard'), (6,1,N'Kalpitiya Naval Base',N'Navy')) AS v(trip, cid, nm, typ)
JOIN #m_trip mt ON mt.pdf = v.trip;
INSERT INTO #log VALUES (N'trip_safety_contacts', 7, @@ROWCOUNT);

INSERT INTO trip_safety_contact_phones (trip_id, contact_id, phone_number)
SELECT mt.id, v.cid, v.num FROM (VALUES (1,1,'0773000001'), (2,1,'119'), (3,1,'0773000003'), (3,2,'1990'), (4,1,'119'), (5,1,'0773000005'), (6,1,'0773000006'), (6,1,'0113000006')) AS v(trip, cid, num)
JOIN #m_trip mt ON mt.pdf = v.trip;
INSERT INTO #log VALUES (N'trip_safety_contact_phones', 8, @@ROWCOUNT);

INSERT INTO safety_checklists (trip_id, life_jackets_checked, life_jacket_count, first_aid_kit_checked, emergency_contact_number, weather_advisory_status, departure_approved, inspector_name, inspection_time, comments)
SELECT mt.id, v.jack, v.jcount, v.aid, v.phone, 'CLEAR', v.approved, v.inspector, v.itime, v.cmt FROM (VALUES
    (1,1,18,1,'0773000001',1,N'Isuru Bandara','2026-09-05T09:00:00',N'All safety items passed'),
    (2,1,10,1,'119',1,N'Nadeesha Weerasinghe','2026-09-08T09:00:00',N'All safety items passed'),
    (3,1,28,1,'0773000003',1,N'Lahiru Dissanayake','2026-09-12T09:00:00',N'All safety items passed'),
    (4,1,8,1,'119',0,N'Sewwandi Amarasinghe','2026-09-16T09:00:00',N'HOLD: Fire extinguisher failed inspection')
) AS v(trip, jack, jcount, aid, phone, approved, inspector, itime, cmt)
JOIN #m_trip mt ON mt.pdf = v.trip;
INSERT INTO #log VALUES (N'safety_checklists (inspected trips only)', 6, @@ROWCOUNT);

INSERT INTO safety_checklist_items (checklist_id, item_name, result)
SELECT sc.id, v.item, v.res FROM (VALUES
    (1,N'Life jackets','Pass'),
    (1,N'First-aid kit','Pass'),
    (1,N'Fire extinguisher','Pass'),
    (1,N'Radio and communication','Pass'),
    (1,N'Engine and fuel check','Pass'),
    (2,N'Life jackets','Pass'),
    (2,N'First-aid kit','Pass'),
    (2,N'Fire extinguisher','Pass'),
    (2,N'Radio and communication','Pass'),
    (2,N'Engine and fuel check','Pass'),
    (3,N'Life jackets','Pass'),
    (3,N'First-aid kit','Pass'),
    (3,N'Fire extinguisher','Pass'),
    (3,N'Radio and communication','Pass'),
    (3,N'Engine and fuel check','Pass'),
    (4,N'Life jackets','Pass'),
    (4,N'First-aid kit','Pass'),
    (4,N'Fire extinguisher','Fail'),
    (4,N'Radio and communication','Pass'),
    (4,N'Engine and fuel check','Pass')
) AS v(trip, item, res)
JOIN #m_trip mt ON mt.pdf = v.trip JOIN safety_checklists sc ON sc.trip_id = mt.id;
INSERT INTO #log VALUES (N'safety_checklist_items', 20, @@ROWCOUNT);

INSERT INTO audit_logs (table_name, record_id, action, old_value, new_value, changed_by, changed_at)
SELECT v.tbl, CAST(COALESCE(mb.id, mp.id, mbt.id) AS VARCHAR(50)), v.act, v.oldv, v.newv, v.changer, v.changed FROM (VALUES
    ('Booking',12,'INSERT',NULL,N'Pending','sanduni.peiris@boatsafari.lk','2026-09-03T10:12:00'),
    ('Booking',1,'UPDATE',N'Pending',N'Confirmed','kavindu.jayasinghe@boatsafari.lk','2026-08-20T09:30:00'),
    ('Booking',6,'UPDATE',N'Confirmed',N'Cancelled','kavindu.jayasinghe@boatsafari.lk','2026-09-16T08:45:00'),
    ('Promotion',4,'UPDATE',N'Published',N'Archived','hiruni.desilva@boatsafari.lk','2026-07-01T09:00:00'),
    ('Boat',4,'UPDATE',N'Cleared',N'Not Cleared','sewwandi.amarasinghe@boatsafari.lk','2026-09-16T08:30:00'),
    ('Boat',3,'UPDATE',N'Active',N'In Maintenance','sampath.kumara@boatsafari.lk','2026-09-14T14:20:00')
) AS v(tbl, rid, act, oldv, newv, changer, changed)
LEFT JOIN #m_booking mb ON v.tbl = 'Booking' AND mb.pdf = v.rid
LEFT JOIN #m_promo mp ON v.tbl = 'Promotion' AND mp.pdf = v.rid
LEFT JOIN #m_boat mbt ON v.tbl = 'Boat' AND mbt.pdf = v.rid;
INSERT INTO #log VALUES (N'audit_logs', 6, @@ROWCOUNT);

IF @triggerWasOn = 1 ENABLE TRIGGER dbo.trg_bookings_audit ON dbo.bookings;
COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

-- RESULT 1: rows added per table (addedRows must equal pdfRows)
SELECT step, pdfRows, addedRows, CASE WHEN pdfRows = addedRows THEN 'OK' ELSE 'CHECK' END AS result FROM #log;

-- RESULT 2: total rows now in each table
SELECT 'customers' AS tbl, COUNT(*) AS totalRows FROM customers UNION ALL SELECT 'staff', COUNT(*) FROM staff
UNION ALL SELECT 'boats', COUNT(*) FROM boats UNION ALL SELECT 'trips', COUNT(*) FROM trips
UNION ALL SELECT 'bookings', COUNT(*) FROM bookings UNION ALL SELECT 'promotions', COUNT(*) FROM promotions
UNION ALL SELECT 'reviews', COUNT(*) FROM reviews UNION ALL SELECT 'reports', COUNT(*) FROM reports
UNION ALL SELECT 'audit_logs', COUNT(*) FROM audit_logs;

-- RESULT 3: the shifted trip dates (Scheduled trips are bookable from this date)
SELECT t.id, t.trip_date, t.departure_time, t.status, r.origin, r.destination, t.booked_seats, t.passenger_capacity
FROM trips t JOIN routes r ON r.id = t.route_id WHERE t.id >= (SELECT MIN(id) FROM #m_trip) ORDER BY t.id;

DROP TABLE #log, #m_customer, #m_staff, #m_route, #m_guide, #m_crew, #m_boat, #m_trip, #m_promo, #m_booking;
GO

